"""add generation_candidates, model_calls, chunk lineage

Revision ID: 117e4e58d6e1
Revises: 7373f061034e
Create Date: 2026-08-11 16:13:21.178179

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '117e4e58d6e1'
down_revision: str | None = '7373f061034e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_calls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('requested_model', sa.String(length=128), nullable=False),
    sa.Column('resolved_model', sa.String(length=128), nullable=False),
    sa.Column('profile', sa.String(length=64), nullable=False),
    sa.Column('prompt_template_hash', sa.String(length=64), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=False),
    sa.Column('sampling_params', sa.JSON(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('result_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_calls_project_id'), 'model_calls', ['project_id'], unique=False)
    op.create_index(op.f('ix_model_calls_request_fingerprint'), 'model_calls', ['request_fingerprint'], unique=False)
    op.create_table('generation_candidates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('source_document_id', sa.String(length=64), nullable=False),
    sa.Column('source_group_id', sa.String(length=255), nullable=True),
    sa.Column('split', sa.String(length=32), nullable=False),
    sa.Column('source_span_ids', sa.JSON(), nullable=False),
    sa.Column('topology', sa.String(length=32), nullable=False),
    sa.Column('task_family', sa.String(length=64), nullable=False),
    sa.Column('prompt_template_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_template_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_template_hash', sa.String(length=64), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('profile', sa.String(length=64), nullable=False),
    sa.Column('call_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('raw_output_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('candidate_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cand_fingerprint', 'generation_candidates', ['call_fingerprint'], unique=False)
    op.create_index(op.f('ix_generation_candidates_candidate_hash'), 'generation_candidates', ['candidate_hash'], unique=False)
    op.create_index(op.f('ix_generation_candidates_chunk_id'), 'generation_candidates', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_generation_candidates_project_id'), 'generation_candidates', ['project_id'], unique=False)
    op.create_index(op.f('ix_generation_candidates_source_document_id'), 'generation_candidates', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_generation_candidates_source_group_id'), 'generation_candidates', ['source_group_id'], unique=False)
    op.add_column('chunks', sa.Column('source_document_id', sa.String(length=64), nullable=False))
    op.add_column('chunks', sa.Column('source_group_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_chunks_source_document_id'), 'chunks', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_chunks_source_group_id'), 'chunks', ['source_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_source_group_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_source_document_id'), table_name='chunks')
    op.drop_column('chunks', 'source_group_id')
    op.drop_column('chunks', 'source_document_id')
    op.drop_index(op.f('ix_generation_candidates_source_group_id'), table_name='generation_candidates')
    op.drop_index(op.f('ix_generation_candidates_source_document_id'), table_name='generation_candidates')
    op.drop_index(op.f('ix_generation_candidates_project_id'), table_name='generation_candidates')
    op.drop_index(op.f('ix_generation_candidates_chunk_id'), table_name='generation_candidates')
    op.drop_index(op.f('ix_generation_candidates_candidate_hash'), table_name='generation_candidates')
    op.drop_index('ix_cand_fingerprint', table_name='generation_candidates')
    op.drop_table('generation_candidates')
    op.drop_index(op.f('ix_model_calls_request_fingerprint'), table_name='model_calls')
    op.drop_index(op.f('ix_model_calls_project_id'), table_name='model_calls')
    op.drop_table('model_calls')
    # ### end Alembic commands ###
