"""add job_checkpoints durable stage checkpoints

Revision ID: 419ae764fdea
Revises: 117e4e58d6e1
Create Date: 2026-08-11 20:05:19.035540

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "419ae764fdea"
down_revision: str | None = "117e4e58d6e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_checkpoints",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("stage_name", sa.String(length=64), nullable=False),
        sa.Column("stage_version", sa.String(length=64), nullable=False),
        sa.Column("checkpoint_key", sa.String(length=255), nullable=False),
        sa.Column("checkpoint_sequence", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("output_artifact_ids", sa.JSON(), nullable=False),
        sa.Column("output_summary", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.String(length=255), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_checkpoint_job_stage", "job_checkpoints", ["job_id", "stage_name"], unique=False
    )
    op.create_index("ix_checkpoint_worker", "job_checkpoints", ["worker_id"], unique=False)
    op.create_index(op.f("ix_job_checkpoints_job_id"), "job_checkpoints", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_checkpoints_job_id"), table_name="job_checkpoints")
    op.drop_index("ix_checkpoint_worker", table_name="job_checkpoints")
    op.drop_index("ix_checkpoint_job_stage", table_name="job_checkpoints")
    op.drop_table("job_checkpoints")
    # ### end Alembic commands ###
