"""initial schema baseline

Revision ID: 7373f061034e
Revises: 
Create Date: 2026-08-09 12:40:07.673895

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7373f061034e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('principal', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('cost_ledger',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('price_snapshot_date', sa.String(length=32), nullable=True),
    sa.Column('price_input_per_m', sa.Float(), nullable=False),
    sa.Column('price_output_per_m', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_job', 'cost_ledger', ['job_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_principal', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('default_profile', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_principal'), 'projects', ['owner_principal'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('dataset_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('semantic_version', sa.String(length=32), nullable=False),
    sa.Column('parent_version_id', sa.String(length=64), nullable=True),
    sa.Column('manifest_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('quality_report_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('dataset_card_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('source_manifest_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('license_report_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('privacy_report_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('train_count', sa.Integer(), nullable=False),
    sa.Column('validation_count', sa.Integer(), nullable=False),
    sa.Column('test_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('release_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_versions_project_id'), 'dataset_versions', ['project_id'], unique=False)
    op.create_index('ix_version_project', 'dataset_versions', ['project_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('owner_principal', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('input_config_hash', sa.String(length=64), nullable=True),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('cancellation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('actual_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_job_project', 'jobs', ['project_id'], unique=False)
    op.create_index('ix_job_state', 'jobs', ['state'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('original_name', sa.String(length=1024), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_locator_redacted', sa.String(length=1024), nullable=False),
    sa.Column('acquisition_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('declared_license', sa.String(length=255), nullable=True),
    sa.Column('detected_license', sa.String(length=255), nullable=True),
    sa.Column('license_status', sa.String(length=32), nullable=False),
    sa.Column('privacy_classification', sa.String(length=64), nullable=False),
    sa.Column('language_candidates', sa.JSON(), nullable=False),
    sa.Column('page_or_sheet_count', sa.Integer(), nullable=True),
    sa.Column('intake_status', sa.String(length=32), nullable=False),
    sa.Column('artifact_id_original', sa.String(length=64), nullable=True),
    sa.Column('group_key', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_group_key'), 'source_documents', ['group_key'], unique=False)
    op.create_index(op.f('ix_source_documents_project_id'), 'source_documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_source_documents_sha256'), 'source_documents', ['sha256'], unique=False)
    op.create_index('ix_source_project', 'source_documents', ['project_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('structured_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_job_seq', 'job_events', ['job_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('parsed_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_document_id', sa.String(length=64), nullable=False),
    sa.Column('parser_name', sa.String(length=128), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('parser_config_hash', sa.String(length=64), nullable=False),
    sa.Column('canonical_docling_json_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('markdown_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('text_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('diagnostics_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('extraction_status', sa.String(length=32), nullable=False),
    sa.Column('extraction_quality_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_documents_source_document_id'), 'parsed_documents', ['source_document_id'], unique=False)
    op.create_index('ix_parsed_source', 'parsed_documents', ['source_document_id'], unique=False)
    op.create_table('training_examples',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('topology', sa.String(length=32), nullable=False),
    sa.Column('system_messages', sa.JSON(), nullable=False),
    sa.Column('prompt_messages', sa.JSON(), nullable=False),
    sa.Column('chosen_messages', sa.JSON(), nullable=False),
    sa.Column('rejected_messages', sa.JSON(), nullable=False),
    sa.Column('label_or_target', sa.JSON(), nullable=True),
    sa.Column('source_span_ids', sa.JSON(), nullable=False),
    sa.Column('source_document_ids', sa.JSON(), nullable=False),
    sa.Column('generation_candidate_ids', sa.JSON(), nullable=False),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('quality_dimensions', sa.JSON(), nullable=False),
    sa.Column('defect_taxonomy', sa.JSON(), nullable=False),
    sa.Column('trainer_visible_metadata', sa.JSON(), nullable=False),
    sa.Column('private_audit_metadata', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('split', sa.String(length=32), nullable=True),
    sa.Column('version_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_example_project', 'training_examples', ['project_id'], unique=False)
    op.create_index('ix_example_status', 'training_examples', ['quality_status'], unique=False)
    op.create_index(op.f('ix_training_examples_content_hash'), 'training_examples', ['content_hash'], unique=False)
    op.create_index(op.f('ix_training_examples_project_id'), 'training_examples', ['project_id'], unique=False)
    op.create_index(op.f('ix_training_examples_split'), 'training_examples', ['split'], unique=False)
    op.create_index(op.f('ix_training_examples_version_id'), 'training_examples', ['version_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('parsed_document_id', sa.String(length=64), nullable=False),
    sa.Column('split_group_id', sa.String(length=64), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('heading_path', sa.JSON(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('structural_type', sa.String(length=64), nullable=False),
    sa.Column('main_text', sa.Text(), nullable=False),
    sa.Column('rendered_context', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('source_span_ids', sa.JSON(), nullable=False),
    sa.Column('chunker_name', sa.String(length=128), nullable=False),
    sa.Column('chunker_version', sa.String(length=64), nullable=False),
    sa.Column('chunker_config_hash', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parsed_document_id'], ['parsed_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunk_parsed', 'chunks', ['parsed_document_id'], unique=False)
    op.create_index(op.f('ix_chunks_parsed_document_id'), 'chunks', ['parsed_document_id'], unique=False)
    op.create_index(op.f('ix_chunks_sha256'), 'chunks', ['sha256'], unique=False)
    op.create_index(op.f('ix_chunks_split_group_id'), 'chunks', ['split_group_id'], unique=False)
    op.create_table('quality_assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('example_id', sa.String(length=64), nullable=False),
    sa.Column('validator_name', sa.String(length=128), nullable=False),
    sa.Column('validator_version', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('concise_rationale', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['example_id'], ['training_examples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_assessments_example_id'), 'quality_assessments', ['example_id'], unique=False)
    op.create_table('source_spans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('parsed_document_id', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.String(length=1024), nullable=False),
    sa.Column('element_reference', sa.String(length=255), nullable=False),
    sa.Column('character_start', sa.Integer(), nullable=True),
    sa.Column('character_end', sa.Integer(), nullable=True),
    sa.Column('quoted_text', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['parsed_document_id'], ['parsed_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_spans_parsed_document_id'), 'source_spans', ['parsed_document_id'], unique=False)
    op.create_index('ix_span_parsed', 'source_spans', ['parsed_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_span_parsed', table_name='source_spans')
    op.drop_index(op.f('ix_source_spans_parsed_document_id'), table_name='source_spans')
    op.drop_table('source_spans')
    op.drop_index(op.f('ix_quality_assessments_example_id'), table_name='quality_assessments')
    op.drop_table('quality_assessments')
    op.drop_index(op.f('ix_chunks_split_group_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_sha256'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_parsed_document_id'), table_name='chunks')
    op.drop_index('ix_chunk_parsed', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_training_examples_version_id'), table_name='training_examples')
    op.drop_index(op.f('ix_training_examples_split'), table_name='training_examples')
    op.drop_index(op.f('ix_training_examples_project_id'), table_name='training_examples')
    op.drop_index(op.f('ix_training_examples_content_hash'), table_name='training_examples')
    op.drop_index('ix_example_status', table_name='training_examples')
    op.drop_index('ix_example_project', table_name='training_examples')
    op.drop_table('training_examples')
    op.drop_index('ix_parsed_source', table_name='parsed_documents')
    op.drop_index(op.f('ix_parsed_documents_source_document_id'), table_name='parsed_documents')
    op.drop_table('parsed_documents')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_index('ix_event_job_seq', table_name='job_events')
    op.drop_table('job_events')
    op.drop_index('ix_source_project', table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_sha256'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_project_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_group_key'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_index('ix_job_state', table_name='jobs')
    op.drop_index('ix_job_project', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_version_project', table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_project_id'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_principal'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_cost_job', table_name='cost_ledger')
    op.drop_table('cost_ledger')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
