"""add example_revisions and review_decisions (WP H1/H2) + version membership

Revision ID: c41a2b3e4f50
Revises: 419ae764fdea
Create Date: 2026-08-12 16:10:00.000000

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c41a2b3e4f50"
down_revision: str | None = "419ae764fdea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "example_revisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("example_logical_id", sa.String(length=64), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("parent_revision_id", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("review_state", sa.String(length=32), nullable=True),
        sa.Column("concurrency_token", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_example_revisions_concurrency_token"),
        "example_revisions",
        ["concurrency_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_example_revisions_example_logical_id"),
        "example_revisions",
        ["example_logical_id"],
        unique=False,
    )
    op.create_index(
        "ix_revision_example", "example_revisions", ["example_logical_id"], unique=False
    )
    op.create_index(
        "ix_revision_example_rev",
        "example_revisions",
        ["example_logical_id", "revision_id"],
        unique=False,
    )

    op.create_table(
        "review_decisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("example_id", sa.String(length=64), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_principal", sa.String(length=255), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("concurrency_token", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_decisions_example_id"), "review_decisions", ["example_id"], unique=False
    )
    op.create_index("ix_review_example", "review_decisions", ["example_id"], unique=False)

    op.add_column("dataset_versions", sa.Column("member_example_ids", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dataset_versions", "member_example_ids")
    op.drop_index("ix_review_example", table_name="review_decisions")
    op.drop_index(op.f("ix_review_decisions_example_id"), table_name="review_decisions")
    op.drop_table("review_decisions")
    op.drop_index("ix_revision_example_rev", table_name="example_revisions")
    op.drop_index("ix_revision_example", table_name="example_revisions")
    op.drop_index(op.f("ix_example_revisions_example_logical_id"), table_name="example_revisions")
    op.drop_index(op.f("ix_example_revisions_concurrency_token"), table_name="example_revisions")
    op.drop_table("example_revisions")
    # ### end Alembic commands ###
