#!/usr/bin/env python3
"""Visual-asset governance gate (contract §15).

The repo-wide, blocking companion to scripts/check_assets.py (which owns
diagram source/render parity and count-free claims) and
scripts/visuals/verify_visual_assets.py (which owns the §13 screenshot
contract against a captured workspace). This gate covers what those two do
not, per the §15 checklist:

- required logo/brand assets exist (light/dark variants, monochrome,
  favicon, social previews, README banner set);
- every brand SVG parses and contains no external font URLs, no embedded
  font binaries, no private paths/secrets, no count claims that rot;
- image dimensions match their contracts (favicon rasters, social
  previews, README banner geometry);
- every image referenced by README/docs/overrides resolves to a file,
  and every committed screenshot/diagram/brand raster is referenced
  (no orphans);
- file-size budgets (§15): README-embedded stills < 350 KB, social
  previews < 500 KB, GIF < 5 MB, SVG logo < 50 KB;
- favicon is wired into mkdocs.yml;
- screenshots carry no private metadata (paths, emails, tokens);
- motion tokens: no duration outside tokens.css's allowlist, no looping
  animation in site CSS (docs/design-system/motion.md M1/M5).

Python-only, deterministic, no network. Exit 0 = clean; exit 1 lists every
finding. Wired as a blocking CI step (ci.yml docs job) and asserted by
tests/public/test_visual_asset_governance.py (§22).

Usage:
    uv run --no-sync python scripts/check_visual_assets.py
"""

from __future__ import annotations

import re
import struct
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ASSETS = REPO_ROOT / "docs" / "assets"
BRAND = ASSETS / "brand"
SHOTS = ASSETS / "screenshots"

# ---- §15 budgets ("preferably <" numbers; the gate treats them as the
# ---- contract they document — optimize responsibly, never degrade quality
# ---- solely to meet them, which the palette pipeline in optimize_assets.py
# ---- achieves without visible loss).
README_STILL_MAX = 350_000
SOCIAL_PREVIEW_MAX = 500_000
GIF_MAX = 5_000_000
SVG_LOGO_MAX = 50_000

# §15 checklist: required logo assets. Every file is generated by
# scripts/visuals/build_brand_assets.py; build --check enforces byte-freshness,
# this enforces presence + sanity.
REQUIRED_BRAND = [
    # core identity, light/dark + monochrome variants (§15 "light/dark logo
    # variants")
    "logo-primary.svg",
    "logo-primary-dark.svg",
    "logo-monochrome-light.svg",
    "logo-monochrome-dark.svg",
    "logo-symbol.svg",
    "logo-wordmark.svg",
    "logo-stacked.svg",
    # favicon set (raster + vector)
    "favicon.svg",
    "favicon-32.png",
    "favicon-192.png",
    "app-icon.png",
    # README banner: light/dark × wide/narrow (§10.1)
    "github-readme-banner.svg",
    "github-readme-banner-dark.svg",
    "github-readme-banner-narrow.svg",
    "github-readme-banner-narrow-dark.svg",
    # social previews: raster is what unfurlers consume; -source is the SVG
    # the raster is rendered from (§15 "source/generated asset pairing")
    "docs-social-preview.png",
    "docs-social-preview-source.svg",
    "github-social-preview.png",
    "github-social-preview-source.svg",
    "release-social-preview.png",
    "release-social-preview-source.svg",
    "github-avatar.png",
]

REQUIRED_SCREENSHOTS = [
    "web-console-overview.png",
    "project-source-view.png",
    "provenance-lineage.png",
    "quality-gates.png",
    "preference-review.png",
    "export-release.png",
    "mobile-overview.png",
    "dark-mode-overview.png",
    "offline-demo.gif",
    "offline-demo-poster.png",
]

# (width, height) contracts for the raster assets that have one.
PNG_DIMENSIONS = {
    "brand/favicon-32.png": (32, 32),
    "brand/favicon-192.png": (192, 192),
    "brand/docs-social-preview.png": (1200, 630),
    "brand/github-social-preview.png": (1280, 640),
    # release card shares the docs card geometry (RASTER_TARGETS in
    # build_brand_assets.py renders it at 1200x630)
    "brand/release-social-preview.png": (1200, 630),
}

# README-embedded stills (§15 README budget): the README embeds the canonical
# §13.2 section crops plus the GIF poster; every committed screenshot is held
# to the same budget by check_budgets().
README_STILLS = [
    "screenshots/offline-demo-poster.png",
]

# §13.3/§15 metadata privacy: scan ONLY PNG text chunks (tEXt/iTXt/zTXt via
# PIL info) — decoding compressed pixel bytes as text yields random false
# positives.
_PRIVATE_PATTERNS = [
    (re.compile(r"/(?:Users|home)/[A-Za-z0-9_.-]+"), "absolute home path"),
    (re.compile(r"\b[\w.+-]+@[\w-]+\.[\w.]+\b"), "email address"),
    (re.compile(r"\b(?:sk|ghp|gho|github_pat|xoxb|AKIA)[A-Za-z0-9_-]{10,}\b"), "credential token"),
]

# URLs that would make brand SVGs depend on third-party availability or
# track viewers (§15 "no external font URLs inside logo SVGs"; §19 fonts).
# The SVG namespaces (www.w3.org/2000/svg et al.) are identifiers, not
# fetched resources — they are the one allowed absolute URL.
_EXTERNAL_URL = re.compile(r"https?://[^\s\"'<>]+", re.IGNORECASE)
_ALLOWED_URL_SUBSTRINGS = ("w3.org",)

_FONT_BINARY_MAGIC = (b"\x00\x01\x00\x00", b"OTTO", b"true", b"ttcf")  # ttf/otf/collection

# Motion governance (§14 via design-system/motion.md): site CSS may animate
# only on the token durations; nothing may loop (M1: no ambient motion).
_TOKEN_DURATIONS = {"120ms", "180ms", "280ms", "0.01ms"}
_DURATION_RE = re.compile(r"(?<![\w-])(\d+(?:\.\d+)?m?s)\b")
_LOOPING_RE = re.compile(r"infinite")
_SITE_CSS = [
    ASSETS / "design-system" / "tokens.css",
    ASSETS / "design-system" / "components.css",
]


def _png_size(data: bytes) -> tuple[int, int] | None:
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    return struct.unpack(">II", data[16:24])


def _md_and_override_files() -> list[Path]:
    files = [REPO_ROOT / "README.md", REPO_ROOT / "overrides" / "main.html"]
    files.extend(p for p in (REPO_ROOT / "docs").rglob("*.md") if "assets" not in p.parts)
    return [f for f in files if f.is_file()]


# --------------------------------------------------------------------------
# checks — each returns a list of findings
# --------------------------------------------------------------------------


def check_required_assets() -> list[str]:
    problems = []
    for name in REQUIRED_BRAND:
        p = BRAND / name
        if not p.is_file() or p.stat().st_size == 0:
            problems.append(f"missing required brand asset: brand/{name}")
    for name in REQUIRED_SCREENSHOTS:
        p = SHOTS / name
        if not p.is_file() or p.stat().st_size == 0:
            problems.append(f"missing required screenshot: screenshots/{name}")
    return problems


def check_svg_hygiene() -> list[str]:
    problems = []
    for svg in sorted(BRAND.glob("*.svg")):
        rel = svg.relative_to(REPO_ROOT)
        if svg.stat().st_size > SVG_LOGO_MAX:
            problems.append(f"{rel}: {svg.stat().st_size} bytes > {SVG_LOGO_MAX} SVG logo budget")
        data = svg.read_bytes()
        try:
            root = ET.fromstring(data)
        except ET.ParseError as exc:
            problems.append(f"{rel}: invalid XML ({exc})")
            root = None
        if root is not None and root.tag != "{http://www.w3.org/2000/svg}svg":
            problems.append(f"{rel}: root element is not <svg>")
        # byte-level hygiene runs regardless of XML validity — a malformed
        # SVG must not escape the font-binary / external-URL scans
        if b"@font-face" in data:
            problems.append(f"{rel}: embeds @font-face")
        for magic in _FONT_BINARY_MAGIC:
            if magic in data:
                problems.append(f"{rel}: contains embedded font binary ({magic!r})")
        if b"\x00" in data:
            problems.append(f"{rel}: contains NUL bytes (binary content in SVG)")
        text = data.decode("utf-8", errors="replace")
        for m in _EXTERNAL_URL.finditer(text):
            url = m.group(0).rstrip(".")
            if any(host in url for host in _ALLOWED_URL_SUBSTRINGS):
                continue
            problems.append(f"{rel}: external URL {url!r} in SVG")
        # metadata privacy (§15): no private paths/emails in SVG text
        for pattern, label in _PRIVATE_PATTERNS:
            if pattern.search(text):
                problems.append(f"{rel}: {label} in SVG source")
    return problems


def check_png_metadata_privacy() -> list[str]:
    """§13.3 screenshot privacy + §15 metadata privacy, repo-wide."""
    try:
        from PIL import Image
    except ImportError:  # pragma: no cover - pillow is a dev/visuals dep
        return ["pillow not installed — cannot scan PNG metadata (install visuals extra)"]
    problems = []
    for png in sorted(ASSETS.rglob("*.png")):
        rel = png.relative_to(REPO_ROOT)
        try:
            img = Image.open(png)
        except Exception as exc:  # noqa: BLE001 - any decode failure is a finding
            problems.append(f"{rel}: unreadable image ({exc})")
            continue
        for key, value in (img.info or {}).items():
            if not isinstance(value, str):
                continue
            for pattern, label in _PRIVATE_PATTERNS:
                if pattern.search(value):
                    problems.append(f"{rel}: {label} in PNG metadata key {key!r}")
    return problems


def check_dimensions() -> list[str]:
    problems = []
    for rel, expected in PNG_DIMENSIONS.items():
        p = REPO_ROOT / "docs" / "assets" / rel
        if not p.is_file():
            continue  # missing-file already reported by check_required_assets
        got = _png_size(p.read_bytes())
        if got != expected:
            problems.append(f"assets/{rel}: {got} != expected {expected}")
    return problems


def check_budgets() -> list[str]:
    problems = []
    for rel in README_STILLS:
        p = ASSETS / rel
        if p.is_file() and p.stat().st_size > README_STILL_MAX:
            problems.append(
                f"assets/{rel}: {p.stat().st_size // 1024} KB > {README_STILL_MAX // 1024} KB"
                " README still budget"
            )
    for p in sorted(SHOTS.glob("*.png")):
        # every committed screenshot is embedded somewhere public (docs or
        # README) — hold all of them to the still budget
        if p.stat().st_size > README_STILL_MAX:
            problems.append(
                f"assets/screenshots/{p.name}: {p.stat().st_size // 1024} KB >"
                f" {README_STILL_MAX // 1024} KB screenshot budget"
            )
    for name in (
        "brand/docs-social-preview.png",
        "brand/github-social-preview.png",
        "brand/release-social-preview.png",
        "brand/github-avatar.png",
    ):
        p = BRAND / Path(name).name
        if p.is_file() and p.stat().st_size > SOCIAL_PREVIEW_MAX:
            problems.append(
                f"assets/brand/{p.name}: {p.stat().st_size // 1024} KB >"
                f" {SOCIAL_PREVIEW_MAX // 1024} KB social-preview budget"
            )
    gif = SHOTS / "offline-demo.gif"
    if gif.is_file() and gif.stat().st_size > GIF_MAX:
        problems.append(
            f"assets/screenshots/{gif.name}: {gif.stat().st_size // 1024} KB >"
            f" {GIF_MAX // 1024} KB GIF budget"
        )
    return problems


def check_references() -> list[str]:
    """Every image ref in README/docs/overrides resolves; every committed
    screenshot/diagram PNG is referenced somewhere (no orphans)."""
    public = "\n".join(f.read_text(encoding="utf-8") for f in _md_and_override_files())
    # built-site references too (docs/**/*.css can url() assets)
    css = "\n".join(p.read_text(encoding="utf-8") for p in sorted(ASSETS.rglob("*.css")))
    everything = public + "\n" + css
    problems = []
    # 1. every referenced image exists
    refs = set(re.findall(r"(?:assets/[\w./-]+\.(?:png|svg|gif|jpg|webp))", everything))
    for ref in sorted(refs):
        if not (REPO_ROOT / "docs" / ref).is_file():
            problems.append(f"broken image reference: {ref}")
    # 2. every committed raster is referenced somewhere public OR is an
    # externally-consumed asset (§15 pairing): brand rasters the *platforms*
    # fetch by convention — favicon.ico fallbacks, GitHub org avatar, repo
    # social preview uploaded through Settings — are not embeddable in repo
    # text; their presence is required by check_required_assets instead.
    EXTERNALLY_CONSUMED = {
        "assets/brand/app-icon.png",
        "assets/brand/favicon-32.png",
        "assets/brand/favicon-192.png",
        "assets/brand/github-avatar.png",
        "assets/brand/github-social-preview.png",
        "assets/brand/release-social-preview.png",
    }
    for png in sorted(ASSETS.rglob("*.png")):
        rel = f"assets/{png.relative_to(ASSETS)}"
        if rel in EXTERNALLY_CONSUMED:
            continue
        if rel not in everything:
            problems.append(f"orphan asset (referenced nowhere public): {rel}")
    return problems


def check_favicon_wiring() -> list[str]:
    problems = []
    mkdocs = (REPO_ROOT / "mkdocs.yml").read_text(encoding="utf-8")
    if not re.search(r"favicon:\s*assets/brand/favicon\.svg", mkdocs):
        problems.append("mkdocs.yml theme.favicon does not point at assets/brand/favicon.svg")
    return problems


def check_motion_tokens() -> list[str]:
    """§14: site CSS animates only on tokens.css durations; nothing loops."""
    problems = []
    if not _SITE_CSS[0].is_file():
        return problems  # design system not present yet; nothing to govern
    for css in _SITE_CSS:
        rel = css.relative_to(REPO_ROOT)
        text = css.read_text(encoding="utf-8")
        if _LOOPING_RE.search(text):
            problems.append(f"{rel}: infinite animation loop (motion.md M1 forbids ambient motion)")
        if css.name == "components.css":
            for m in _DURATION_RE.finditer(text):
                tok = m.group(1)
                if tok.endswith("s") and not tok.endswith("ms"):
                    continue  # var() references and unitless are handled below
                if tok not in _TOKEN_DURATIONS and tok not in {"1s", "0.2s"}:
                    problems.append(
                        f"{rel}: duration {tok!r} outside the tokens.css motion allowlist"
                        " (docs/design-system/motion.md)"
                    )
    return problems


def main() -> int:
    suites = {
        "required assets": check_required_assets(),
        "svg hygiene": check_svg_hygiene(),
        "metadata privacy": check_png_metadata_privacy(),
        "dimensions": check_dimensions(),
        "budgets": check_budgets(),
        "references": check_references(),
        "favicon": check_favicon_wiring(),
        "motion tokens": check_motion_tokens(),
    }
    total = 0
    for name, findings in suites.items():
        print(f"=== visual-assets/{name}: {'FAIL' if findings else 'OK'} ===")
        for f in findings:
            print(f"  FAIL: {f}")
        total += len(findings)
    if total:
        print(f"\nFAILED: {total} visual-asset governance problem(s).")
        return 1
    print("\nPASSED: visual-asset governance clean (§15).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
