"""Generate the canonical CLI reference from the real Typer command tree
(defect 3.4, v0.2.1).

v0.2.0 shipped a hand-written ``docs/reference/cli.md`` advertising commands
that do not exist on the Typer application. This script derives the reference
directly from the installed Typer app (via click's introspection), writing a
complete section between explicit markers:

    <!-- BEGIN GENERATED CLI REFERENCE -->
    ...
    <!-- END GENERATED CLI REFERENCE -->

Anything outside the markers is preserved (hand-written prose is allowed
around the generated block).

Usage:
    python scripts/generate_cli_reference.py            # rewrite in place
    python scripts/generate_cli_reference.py --check    # exit 1 on drift
    python scripts/generate_cli_reference.py --stdout   # print, don't write

``--check`` is what CI runs: any CLI change that alters the public surface
must be accompanied by a deliberate regeneration of the reference.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TARGET = REPO_ROOT / "docs" / "reference" / "cli.md"

BEGIN = "<!-- BEGIN GENERATED CLI REFERENCE -->"
END = "<!-- END GENERATED CLI REFERENCE -->"


def _context_class() -> type:
    """Context class from the same click universe the commands belong to.

    Typer >= 0.26 vendors an adapted click (``typer._click``) and builds
    commands/groups on top of it — those objects must be introspected with
    typer's own Context. Older typer builds on the installed ``click``, so
    its Context is used there. Never mix the two universes.
    """
    try:  # typer >= 0.26 vendored click shim
        from typer._click import Context as vendored_context

        return vendored_context
    except ImportError:  # older typer: commands are real-click objects
        import click

        return click.Context


def _subcommands(cmd) -> dict | None:
    """Child mapping for group-like commands, else ``None`` (leaf).

    Duck-typed on purpose: classic ``click.Group`` and typer >= 0.26's
    ``TyperGroup`` (which subclasses a vendored ``click.Command``) both
    expose a ``.commands`` mapping; leaves expose none.
    """
    sub = getattr(cmd, "commands", None)
    if isinstance(sub, dict) and sub:
        return sub
    return None


def _command_tree() -> list[dict]:
    """Walk the real Typer/click tree into a JSON-able structure."""
    ctx_cls = _context_class()

    from knovaryn.interfaces.cli.main import app  # noqa: PLC0415

    root = __import__("typer").main.get_command(app)
    rows: list[dict] = []

    def visit(cmd, path: list[str]) -> None:
        sub = _subcommands(cmd)
        if sub is not None:
            for name in sorted(sub):
                visit(sub[name], [*path, name])
            return
        ctx = ctx_cls(cmd, info_name=" ".join(["knovaryn", *path]))
        lines = cmd.get_help(ctx).splitlines()
        usage = next((ln for ln in lines if ln.strip().startswith("Usage")), "")
        opts: list[str] = []
        positionals: list[str] = []
        for p in cmd.get_params(ctx):
            if getattr(p, "name", None) == "help":
                continue
            if getattr(p, "opts", None):
                opts.append(", ".join(p.opts))
            else:
                positionals.append(p.name.upper())
        synopsis = " ".join(["knovaryn", *path])
        for pos in positionals:
            synopsis += f" {pos}"
        rows.append(
            {
                "path": " ".join(path),
                "synopsis": synopsis,
                "short_help": (getattr(cmd, "short_help", "") or "").strip(),
                "options": opts,
                "usage": usage.strip(),
            }
        )

    visit(root, [])
    return rows


def render(rows: list[dict]) -> str:
    out = [
        BEGIN,
        "",
        "<!-- Generated by scripts/generate_cli_reference.py from the real",
        "     Typer command tree. Do not edit inside this block: rerun the",
        "     script instead. CI fails when this block drifts from the actual",
        "     commands (`--check`). -->",
        "",
        "| Command | Description | Options |",
        "|---|---|---|",
    ]
    for row in rows:
        desc = row["short_help"] or "—"
        opts = ", ".join(f"`{o}`" for o in row["options"]) or "—"
        out.append(f"| `{row['synopsis']}` | {desc} | {opts} |")
    out += ["", END, ""]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail on drift, don't write")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = parser.parse_args()

    rows = _command_tree()
    # Fail closed against the same authority the conformance suite uses: a
    # walk that disagrees with tests/cli/command_tree_snapshot.json means
    # introspection broke (e.g. a typer/click upgrade) — never write docs.
    snap_path = REPO_ROOT / "tests" / "cli" / "command_tree_snapshot.json"
    if snap_path.exists():
        snap_paths = set(json.loads(snap_path.read_text(encoding="utf-8")))
        tree_paths = {r["path"] for r in rows}
        if tree_paths != snap_paths:
            print(
                "FAIL: walked command tree does not match "
                f"{snap_path.relative_to(REPO_ROOT)} "
                f"({len(tree_paths)} vs {len(snap_paths)} commands)\n"
                f"  missing from tree: {sorted(snap_paths - tree_paths)}\n"
                f"  missing from snapshot: {sorted(tree_paths - snap_paths)}\n"
                "Introspection is broken — do NOT regenerate docs until this "
                "matches (check the typer/click versions in .venv).",
                file=sys.stderr,
            )
            return 2

    generated = render(rows)

    if not TARGET.exists():
        print(f"FAIL: {TARGET} does not exist", file=sys.stderr)
        return 2

    text = TARGET.read_text(encoding="utf-8")
    if BEGIN in text and END in text:
        pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
        updated = pattern.sub(lambda _m: generated.rstrip("\n"), text)
    else:
        updated = text.rstrip("\n") + "\n\n" + generated

    if args.stdout:
        sys.stdout.write(updated)
        return 0

    if args.check:
        if updated == text:
            print("cli.md reference is up to date with the Typer command tree")
            return 0
        print(
            "FAIL: docs/reference/cli.md drifted from the real command tree.\n"
            "Run: python scripts/generate_cli_reference.py  (then commit)",
            file=sys.stderr,
        )
        return 1

    TARGET.write_text(updated, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(REPO_ROOT)} ({len(_command_tree())} commands)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
