"""Generate canonical reference documentation from the code (defect 3.4 / §5.1).

Every public reference surface below is rendered from the real registration
point, never hand-maintained:

* REST endpoints        ← FastAPI OpenAPI schema      → docs/reference/rest-api.md
* MCP tool catalogue    ← server tool registration    → docs/reference/mcp-tools.md
* Quality gates         ← default_validators()        → docs/reference/quality-gates.md
* Validation profiles   ← semantic/preference profile registries
                                                      → docs/reference/profiles.md
* Export formats        ← SUPPORTED_FORMATS           → docs/reference/exporters.md (block)
* Configuration keys    ← _DEFAULTS                   → docs/reference/config.md  (block)

Usage:
    python scripts/generate_reference_docs.py            # rewrite in place
    python scripts/generate_reference_docs.py --check    # exit 1 on drift (CI)
"""

from __future__ import annotations

import argparse
import asyncio
import io
import json
import re
import sys
from contextlib import redirect_stdout
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS = REPO_ROOT / "docs" / "reference"

BANNER = (
    "<!-- GENERATED by scripts/generate_reference_docs.py from the real code."
    " Do not edit inside this block: rerun the script instead. -->"
)


def _begin(tag: str) -> str:
    return f"<!-- BEGIN GENERATED {tag} -->"


def _end(tag: str) -> str:
    return f"<!-- END GENERATED {tag} -->"


# ---------------------------------------------------------------- surfaces --

def render_rest_api() -> str:
    from knovaryn.interfaces.rest.app import app as rest_app

    schema = rest_app.openapi()
    rows = []
    for path, methods in sorted(schema.get("paths", {}).items()):
        for method in sorted(methods):
            if method.startswith(("x-", "parameters")):
                continue
            op = methods[method]
            rows.append((method.upper(), path, op.get("summary", "")))
    out = [
        "# Reference — REST API",
        "",
        BANNER,
        "",
        "Endpoints below are generated from the live OpenAPI schema of",
        "`knovaryn.interfaces.rest.app` — the same app `knovaryn server` serves.",
        "Interactive docs ship at `/docs` and `/openapi.json` on a running server.",
        "",
        "When `KNOVARYN_API_TOKEN` is set, every route except the `/v1/health`",
        "probe requires a bearer token with the listed scope(s); see",
        "[security hardening](../security/hardening.md). Error bodies are redacted.",
        "",
        "| Method | Path | Summary |",
        "|---|---|---|",
    ]
    for method, path, summary in rows:
        out.append(f"| `{method}` | `{path}` | {summary or '—'} |")
    return "\n".join(out) + "\n"


def render_mcp_catalogue() -> str:
    from knovaryn.interfaces.mcp.server import build_server

    server = build_server()

    async def _tools():
        return await server.list_tools()

    tools = asyncio.run(_tools())
    rows = sorted(((t.name, (t.description or "").strip().splitlines()[0]
                    if (t.description or "").strip() else "—") for t in tools))
    out = [
        "# Reference — MCP tools",
        "",
        BANNER,
        "",
        "Generated from the Knovaryn MCP server's real tool registration",
        "(`build_server().list_tools()`), so names and counts cannot drift from",
        "what an MCP client actually sees over stdio or streamable HTTP.",
        "",
        f"{len(rows)} registered tools:",
        "",
        "| Tool | Description |",
        "|---|---|",
    ]
    for name, desc in rows:
        out.append(f"| `{name}` | {desc} |")
    out += [
        "",
        "Run with `knovaryn mcp` (stdio by default; `--transport streamable-http`",
        "for remote use behind the bearer-token guard). See",
        "[MCP clients](../guides/mcp-clients.md).",
    ]
    return "\n".join(out) + "\n"


def render_quality_gates() -> str:
    from knovaryn.pipeline.quality.validators import PreferenceValidator, default_validators

    validators = list(default_validators()) + [PreferenceValidator()]
    seen: dict[str, str] = {}
    for v in validators:
        doc = (type(v).__doc__ or "").strip().splitlines()
        seen.setdefault(v.name, doc[0] if doc else "—")
    out = [
        "# Reference — Quality gates",
        "",
        BANNER,
        "",
        "Generated from validator registration (`default_validators()` plus the",
        "preference validator). Every accepted example must pass the enabled",
        "gates; failures carry machine-readable reason codes routed to review or",
        "quarantine. See [quality concepts](../concepts/quality-gates.md).",
        "",
        "| Gate | Purpose |",
        "|---|---|",
    ]
    for name, desc in sorted(seen.items()):
        out.append(f"| `{name}` | {desc} |")
    return "\n".join(out) + "\n"


def render_profiles() -> str:
    from knovaryn.pipeline.quality.profiles import (
        PROFILE_CERTIFIED_PAIRWISE,
        PROFILE_HEURISTIC,
        SPECS,
    )

    out = [
        "# Reference — Validation profiles",
        "",
        BANNER,
        "",
        "Generated from the semantic-profile registry and preference-profile",
        "constants. Exactly these profiles exist; unknown values are rejected at",
        "configuration time.",
        "",
        "## Semantic validation profiles (`quality.semantic_profile`)",
        "",
        "| Profile | Model judge | Network | Limits |",
        "|---|---|---|---|",
    ]
    for name in sorted(SPECS):
        spec = SPECS[name]
        limits = (spec.limits or "").replace("|", "\\|").replace("\n", " ")
        out.append(
            f"| `{name}` | {'yes' if spec.uses_model_judge else 'no'} "
            f"| {'required' if spec.network_required else 'none'} | {limits} |"
        )
    out += [
        "",
        "`offline-fast` is the default and runs anywhere; `certified-semantic`",
        "additionally consults a cited-evidence-only LLM judge through the model",
        "gateway. Deterministic contradictions are final in both profiles; an",
        "unavailable judge yields *unverified*, never *verified*. Benchmark",
        "false-accept/false-reject rates with confidence intervals are published",
        "in the committed benchmark report (`benchmarks/report-0-1-0.md`) — do",
        "not describe results as certified without reproducing them.",
        "",
        "## Preference profiles (`preference.profile`)",
        "",
        "| Profile | Behaviour |",
        "|---|---|",
        f"| `{PROFILE_HEURISTIC}` | Deterministic checks only (default): length band, artifact separability, topology sanity. |",
        f"| `{PROFILE_CERTIFIED_PAIRWISE}` | Adds the certified two-order pairwise judge: randomized presentation, reversed repeat, minimum preference margin, rejected-defect classification; disagreements route to review and full judge lineage is recorded. |",
    ]
    return "\n".join(out) + "\n"


def render_export_formats() -> str:
    from knovaryn.pipeline.export.formats import MEDIA_TYPES, SUPPORTED_FORMATS

    tag = "EXPORT FORMATS"
    lines = [
        _begin(tag),
        "",
        "Format ids are generated from `pipeline.export.formats.SUPPORTED_FORMATS`",
        "— this table cannot drift from what `--format` accepts:",
        "",
        "| Format | Media type |",
        "|---|---|",
    ]
    for fmt in sorted(SUPPORTED_FORMATS):
        lines.append(f"| `{fmt}` | `{MEDIA_TYPES[fmt]}` |")
    lines += [
        f"| `jsonl` | `{MEDIA_TYPES['jsonl']}` |",
        "",
        "`jsonl` is the canonical passthrough (accepted by `--format` alongside",
        "the ids above). Parquet is **not** a `--format` id: it is produced by",
        "the SDK function `knovaryn.pipeline.export.export_parquet` (requires the",
        "`parquet` extra) and by the release bundle's split files when that extra",
        "is installed.",
        "",
        _end(tag),
    ]
    return "\n".join(lines)


def render_config_defaults() -> str:
    from knovaryn.domain.config import _DEFAULTS

    def flatten(prefix: str, node: object, into: list[tuple[str, str]]) -> None:
        if isinstance(node, dict):
            for k, v in sorted(node.items()):
                key = f"{prefix}.{k}" if prefix else str(k)
                flatten(key, v, into)
        else:
            text = json.dumps(node) if not isinstance(node, str) else json.dumps(node)
            into.append((prefix, text))

    pairs: list[tuple[str, str]] = []
    flatten("", dict(_DEFAULTS), pairs)

    tag = "CONFIG DEFAULTS"
    lines = [
        _begin(tag),
        "",
        "Defaults generated from `knovaryn.domain.config._DEFAULTS` — the single",
        "authoritative settings source. `${ENV}` placeholders resolve from the",
        "environment (`KNOVARYN_` prefix).",
        "",
        "| Key | Default |",
        "|---|---|",
    ]
    for key, value in pairs:
        lines.append(f"| `{key}` | `{value}` |")
    lines += ["", _end(tag)]
    return "\n".join(lines)


def render_claim_matrix() -> str:
    """Contract §10: public claim → maturity → code → evidence → limitation."""
    rows = [
        ("CLI lifecycle commands", "stable",
         "src/knovaryn/interfaces/cli/", "tests/test_cli_conformance.py (tree snapshot + docs scan)",
         "Local `run` drives one job in-process; durable multi-worker mode uses `worker`."),
        ("REST API + web console", "stable",
         "src/knovaryn/interfaces/rest/", "tests/test_rest_api.py, tests/test_rest_webconsole.py",
         "Bearer-token auth only when KNOVARYN_API_TOKEN is set."),
        ("Python SDK (Workspace)", "stable",
         "src/knovaryn/application/workspace.py", "tests/test_workspace_control.py",
         "APIs may still gain parameters within the 0.x line."),
        ("MCP stdio server", "experimental",
         "src/knovaryn/interfaces/mcp/server.py",
         "tests/mcp/, scripts/mcp_acceptance_matrix.py",
         "Tool surface may be reshaped before 1.0."),
        ("MCP streamable HTTP (authenticated)", "experimental",
         "src/knovaryn/interfaces/mcp/server.py",
         "scripts/mcp_acceptance_matrix.py (both SDK lines)",
         "Deploy behind the bearer-token guard; not exposed by default."),
        ("Provenance lineage + location precision", "stable",
         "src/knovaryn/application/, src/knovaryn/pipeline/export/gate.py",
         "tests/provenance/",
         "Precision reflects the parser: markdown/text caps at section/chunk."),
        ("Docling parsing (bounding-box spans)", "optional",
         "src/knovaryn/infrastructure/docling/",
         "tests marked `docling`; ADR-0003 resource guard",
         "Requires the `docling` extra and its runtime dependencies."),
        ("Offline semantic validation (`offline-fast`)", "stable",
         "src/knovaryn/pipeline/quality/validators.py", "tests/semantic/",
         "Deterministic checks catch specific contradiction classes only."),
        ("Certified semantic validation (`certified-semantic`)", "optional",
         "src/knovaryn/pipeline/quality/profiles.py", "tests/semantic/ benchmark corpus",
         "Needs a reachable judge provider; unavailable judge ⇒ *unverified*."),
        ("Preference pairs + `certified-pairwise` profile", "alpha",
         "src/knovaryn/pipeline/quality/validators.py", "tests/preference/",
         "Judge-based certification inherits provider limitations."),
        ("Information-gain / preference-signal gates", "alpha",
         "src/knovaryn/pipeline/quality/", "tests/test_validators.py",
         "Heuristic scoring; not a quality guarantee."),
        ("Durable jobs (claim/heartbeat/checkpoint/resume)", "stable",
         "src/knovaryn/pipeline/jobs/, src/knovaryn/infrastructure/database/",
         "tests/chaos/, tests/deployment/",
         "SQLite mode is single-writer; concurrent workers need PostgreSQL."),
        ("PostgreSQL multi-worker queue", "optional",
         "src/knovaryn/infrastructure/database/repositories.py (SKIP LOCKED)",
         "tests/deployment/test_compose_e2e.py claim-exclusivity race",
         "Requires a deployed Postgres; SQLite dialect ignores FOR UPDATE."),
        ("S3-compatible artifact storage", "optional",
         "src/knovaryn/infrastructure/artifacts/s3.py", "tests marked `s3`",
         "Requires the `s3` extra and object-store credentials."),
        ("Hugging Face publishing", "optional",
         "src/knovaryn/infrastructure/publish/hf.py", "publication-gate tests (dry-run default)",
         "Never automatic; license/privacy gate plus explicit confirmation."),
        ("PyPI installation", "stable",
         ".github/workflows/publish.yml (OIDC trusted publishing)",
         "scripts/package_ci.py clean-env battery",
         "First-time setup of PyPI trusted publisher is an owner action."),
        ("Release integrity (checksums, SBOM, notes)", "stable",
         "scripts/release_governance.py, src/knovaryn/pipeline/export/verify_release.py",
         "tests/test_release_governance.py, tests/test_release_integrity.py",
         "GitHub-side settings (labels, environments) are owner actions."),
        ("Docker Compose topology", "stable",
         "deploy/docker/", ".github/workflows/deploy-e2e.yml exact-SHA suite",
         "Weekly/dispatch execution; always runs at release time."),
        ("Kubernetes manifests", "alpha",
         "deploy/kubernetes/", "kustomize build in CI lint path",
         "No automated cluster E2E yet; backup/restore documented as runbook."),
        ("Documentation site & search metadata", "stable",
         "mkdocs.yml, overrides/, docs/", "ci.yml docs job (strict build + links + assets)",
         "Search-engine indexing itself is an owner action (§7.2)."),
        ("Benchmarks (methodology + CIs)", "alpha",
         "benchmarks/bench_suite.py, benchmarks/bench_pipeline.py",
         "benchmarks/report-0-1-0.md (methodology + CIs committed)",
         "Fake-provider throughput ≠ generation throughput; reproduce before relying."),
    ]
    allowed = {"stable", "alpha", "experimental", "optional", "owner action", "not implemented"}
    out = [
        "# Reference — Claim matrix",
        "",
        BANNER,
        "",
        "Generated from the maintainer-curated claim registry in",
        "`scripts/generate_reference_docs.py`: every public claim carries its",
        "maturity, implementation location, automated evidence, and known",
        "limitation. Documentation must never describe an `experimental`,",
        "`optional`, or `owner action` surface as universally operational.",
        "",
        "| Public claim | Maturity | Implementation location | Automated evidence | Known limitation |",
        "|---|---|---|---|---|",
    ]
    for claim, maturity, loc, evidence, limitation in rows:
        assert maturity in allowed, maturity
        esc = lambda s: s.replace("|", "\\|")  # noqa: E731
        out.append(
            f"| {esc(claim)} | `{maturity}` | `{esc(loc)}` | {esc(evidence)} | {esc(limitation)} |"
        )
    return "\n".join(out) + "\n"


# ------------------------------------------------------------------ plumbing


def _replace_block(text: str, begin: str, end: str, rendered: str, target_desc: str) -> str:
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    body = rendered.rstrip("\n")
    if begin in text and end in text:
        return pattern.sub(lambda _m: body, text)
    print(f"note: no markers in {target_desc}; appending block", file=sys.stderr)
    return text.rstrip("\n") + "\n\n" + body + "\n"


def build_all() -> dict[Path, str]:
    """Path → final file content for every generated surface."""
    files: dict[Path, str] = {}
    files[DOCS / "rest-api.md"] = render_rest_api()
    files[DOCS / "mcp-tools.md"] = render_mcp_catalogue()
    files[DOCS / "quality-gates.md"] = render_quality_gates()
    files[DOCS / "profiles.md"] = render_profiles()
    files[DOCS / "claim-matrix.md"] = render_claim_matrix()

    exp_path = DOCS / "exporters.md"
    exp_text = _replace_block(
        exp_path.read_text(encoding="utf-8"),
        _begin("EXPORT FORMATS"),
        _end("EXPORT FORMATS"),
        render_export_formats(),
        str(exp_path.relative_to(REPO_ROOT)),
    ) if exp_path.exists() else None
    if exp_text is not None:
        files[exp_path] = exp_text

    cfg_path = DOCS / "config.md"
    cfg_text = _replace_block(
        cfg_path.read_text(encoding="utf-8"),
        _begin("CONFIG DEFAULTS"),
        _end("CONFIG DEFAULTS"),
        render_config_defaults(),
        str(cfg_path.relative_to(REPO_ROOT)),
    ) if cfg_path.exists() else None
    if cfg_text is not None:
        files[cfg_path] = cfg_text
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail on drift, don't write")
    ap.add_argument("--quiet", action="store_true", help="suppress per-file output")
    args = ap.parse_args()

    # importing the REST/MCP apps prints banner noise; keep stdout clean
    buf = io.StringIO()
    with redirect_stdout(buf):
        files = build_all()

    drifted: list[str] = []
    for path, content in sorted(files.items()):
        old = path.read_text(encoding="utf-8") if path.exists() else ""
        if old != content:
            drifted.append(str(path.relative_to(REPO_ROOT)))
            if not args.check and not args.quiet:
                path.write_text(content, encoding="utf-8")
                print(f"wrote {path.relative_to(REPO_ROOT)}")

    if args.check:
        if drifted:
            print(
                "FAIL: generated reference docs drifted from the code:\n  - "
                + "\n  - ".join(drifted)
                + "\nRun: python scripts/generate_reference_docs.py  (then commit)",
                file=sys.stderr,
            )
            return 1
        print("generated reference docs are up to date with the code")
        return 0

    print(f"done ({len(files)} files, {len(drifted)} updated)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
