#!/usr/bin/env python3
"""Build the complete Knovaryn brand asset family from one source of truth.

Contract §8.4: every brand asset must be reproducible from documented
sources. This script IS that source for the vector family and the raster
derivatives:

* ``logo-primary.svg``          — horizontal lockup, light backgrounds
* ``logo-primary-dark.svg``     — horizontal lockup, dark backgrounds
* ``logo-stacked.svg``          — symbol above wordmark
* ``logo-symbol.svg``           — the Tracemark mark alone
* ``logo-wordmark.svg``         — wordmark alone (ink)
* ``logo-monochrome-dark.svg``  — single-ink lockup (light backgrounds)
* ``logo-monochrome-light.svg`` — single-paper lockup (dark backgrounds)
* ``favicon.svg``               — mark on an ink tile
* ``favicon-32.png`` / ``favicon-192.png`` / ``app-icon.png``
* ``github-avatar.png``
* ``github-readme-banner.svg`` / ``github-readme-banner-dark.svg``
* ``github-readme-banner-narrow.svg`` / ``github-readme-banner-narrow-dark.svg``
* ``github-social-preview-source.svg`` / ``github-social-preview.png``
* ``docs-social-preview.png`` / ``release-social-preview.png``

The letterforms are original monoline geometry (no font dependency, no
embedded raster, no external references). Rasters are rendered with
Playwright's Chromium at fixed device-scale factors — same inputs, same
bytes on any machine with the pinned browser.

Usage:
    uv run --extra visuals python scripts/visuals/build_brand_assets.py
    uv run --extra visuals python scripts/visuals/build_brand_assets.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
BRAND = REPO / "docs" / "assets" / "brand"

# ---------------------------------------------------------------- palette --
INK = "#1C2B33"  # deep blue-slate: structure, text, monochrome marks
TRACE = "#0E7C6B"  # deep verdigris: the provenance route, verification
TRACE_BRIGHT = "#2EB39A"  # trace on dark ground
PAPER = "#FBFAF7"  # warm off-white surface
PAPER_TEXT = "#ECF2EF"  # text-on-dark paper
INK_DEEP = "#0F1B21"  # dark-ground ink (gate core on dark variants)

# ------------------------------------------------------------- geometry ---
# Wordmark grid: stroke 7, cap height 48 (y 10-58), x-height 30, baseline 58.
# The K is the Tracemark: segmented evidence arm -> gate -> solid leg.
K_STEM = "M 14 10 L 14 58"
K_ARM = ("M 44 11 L 39.2 15.3", "M 36.9 17.3 L 29.4 24.0", "M 27.2 26.0 L 22.7 30.0")
K_LEG = "M 22.5 36 L 44 57"
GATE_CX, GATE_CY, GATE_R, GATE_CORE_R = 20.5, 33, 5.8, 2.3

LOWERCASE = (
    "M 59.5 28 L 59.5 58",
    "M 59.5 39 C 59.5 31 62.5 28 66.5 28 C 70.5 28 73.5 31 73.5 38 L 73.5 58",
    "ELLIPSE 94 43 9 15",
    "M 115 28 L 124 58",
    "M 133 28 L 124 58",
    "ELLIPSE 151.5 43 8 15",
    "M 162.5 28 L 162.5 58",
    "M 178 28 L 178 58",
    "M 178 38 C 178 31.5 181.5 28 187.5 28",
    "M 202 28 L 211.5 55",
    "M 221 28 L 212 58 C 210.5 64 205.5 66.5 201 64",
    "M 236 28 L 236 58",
    "M 236 39 C 236 31 239 28 243 28 C 247 28 250 31 250 38 L 250 58",
)

# 64-grid Tracemark symbol (docs/assets/brand/logo-symbol.svg)
SYM_STEM = "M 19 8.5 L 19 55.5"
SYM_ARM = ("M 54 9.5 L 48.6 13.8", "M 45.6 16.1 L 36.8 23.0", "M 33.8 25.3 L 30.6 27.8")
SYM_LEG = "M 30.2 36.4 L 53 55"
SYM_GATE = (25.0, 32.0, 7.0, 2.8)


def _paths(d: str | tuple[str, ...], stroke: str, width: float) -> str:
    if isinstance(d, str):
        d = (d,)
    return "".join(f'<path d="{p}" stroke="{stroke}" stroke-width="{width}"/>' for p in d)


def _lowercase(stroke: str) -> str:
    out = []
    for item in LOWERCASE:
        if item.startswith("ELLIPSE"):
            _, cx, cy, rx, ry = item.split()
            out.append(
                f'<ellipse cx="{cx}" cy="{cy}" rx="{rx}" ry="{ry}" '
                f'stroke="{stroke}" stroke-width="7"/>'
            )
        else:
            out.append(f'<path d="{item}" stroke="{stroke}" stroke-width="7"/>')
    return "".join(out)


def lockup(color: str, route: str, core: str, mono: bool = False) -> str:
    """Horizontal lockup. ``color`` = text + K stem; ``route`` = evidence
    spans / leg / gate; ``core`` = the gate ring's center dot. ``mono``
    collapses the route into the text color."""
    route_color = color if mono else route
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 262 72" role="img" aria-labelledby="lt ld">
  <title id="lt">Knovaryn</title>
  <desc id="ld">The Knovaryn wordmark whose K is the Tracemark symbol: segmented evidence spans converge through a gate ring into one solid verified stroke.</desc>
  <!-- Generated by scripts/visuals/build_brand_assets.py — do not edit; rerun. -->
  <g stroke-linecap="round" stroke-linejoin="round" fill="none">
    {_paths(K_STEM, color, 8.5)}
    {_paths(K_ARM, route_color, 7)}
    {_paths(K_LEG, route_color, 7)}
    {_lowercase(color)}
  </g>
  <circle cx="{GATE_CX}" cy="{GATE_CY}" r="{GATE_R}" fill="{route_color}"/>
  <circle cx="{GATE_CX}" cy="{GATE_CY}" r="{GATE_CORE_R}" fill="{core}"/>
</svg>
"""


def symbol(stem: str, route: str, core: str) -> str:
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-labelledby="st sd">
  <title id="st">Knovaryn symbol</title>
  <desc id="sd">A letter K built from a provenance route: segmented evidence spans converge through a gate ring into one solid verified stroke.</desc>
  <!-- Generated by scripts/visuals/build_brand_assets.py — do not edit; rerun. -->
  <g stroke-linecap="round" fill="none">
    {_paths(SYM_STEM, stem, 9)}
    {_paths(SYM_ARM, route, 8)}
    {_paths(SYM_LEG, route, 8)}
  </g>
  <circle cx="{SYM_GATE[0]}" cy="{SYM_GATE[1]}" r="{SYM_GATE[2]}" fill="{route}"/>
  <circle cx="{SYM_GATE[0]}" cy="{SYM_GATE[1]}" r="{SYM_GATE[3]}" fill="{core}"/>
</svg>
"""


def wordmark(text: str) -> str:
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 262 72" role="img" aria-labelledby="wt wd">
  <title id="wt">Knovaryn</title>
  <desc id="wd">The Knovaryn wordmark: original monoline letterforms whose K echoes the Tracemark symbol.</desc>
  <!-- Generated by scripts/visuals/build_brand_assets.py — do not edit; rerun. -->
  <g stroke-linecap="round" stroke-linejoin="round" fill="none">
    {_paths(K_STEM, text, 8.5)}
    {_paths(K_ARM, text, 7)}
    {_paths(K_LEG, text, 7)}
    {_lowercase(text)}
  </g>
</svg>
"""


def stacked() -> str:
    # mark (64-grid) centered above the wordmark at 0.62 scale
    mark_tx, mark_ty, mark_s = 44.0, 4.0, 1.28
    wm_s = 0.62
    wm_tx = (180 - 253 * wm_s) / 2 - 9.75 * wm_s + 4
    wm_ty = 92.0
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 180 148" role="img" aria-labelledby="kt kd">
  <title id="kt">Knovaryn — stacked logo</title>
  <desc id="kd">The Tracemark symbol above the Knovaryn wordmark.</desc>
  <!-- Generated by scripts/visuals/build_brand_assets.py — do not edit; rerun. -->
  <g transform="translate({mark_tx},{mark_ty}) scale({mark_s})">
    <g stroke-linecap="round" fill="none">
      {_paths(SYM_STEM, INK, 9)}
      {_paths(SYM_ARM, TRACE, 8)}
      {_paths(SYM_LEG, TRACE, 8)}
    </g>
    <circle cx="{SYM_GATE[0]}" cy="{SYM_GATE[1]}" r="{SYM_GATE[2]}" fill="{TRACE}"/>
    <circle cx="{SYM_GATE[0]}" cy="{SYM_GATE[1]}" r="{SYM_GATE[3]}" fill="{PAPER}"/>
  </g>
  <g transform="translate({wm_tx:.2f},{wm_ty}) scale({wm_s})">
    <g stroke-linecap="round" stroke-linejoin="round" fill="none">
      {_paths(K_STEM, INK, 8.5)}
      {_paths(K_ARM, INK, 7)}
      {_paths(K_LEG, INK, 7)}
      {_lowercase(INK)}
    </g>
  </g>
</svg>
"""


def favicon() -> str:
    s = 0.72
    tx = (64 - 43.5 * s) / 2 - 14.5 * s
    ty = (64 - 55.0 * s) / 2 - 4.5 * s
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-labelledby="ft fd">
  <title id="ft">Knovaryn</title>
  <desc id="fd">The Knovaryn Tracemark on an ink tile.</desc>
  <!-- Generated by scripts/visuals/build_brand_assets.py — do not edit; rerun. -->
  <rect width="64" height="64" rx="14" fill="{INK}"/>
  <g transform="translate({tx:.2f},{ty:.2f}) scale({s})">
    <g stroke-linecap="round" fill="none">
      {_paths(SYM_STEM, PAPER, 9)}
      {_paths(SYM_ARM, TRACE_BRIGHT, 8)}
      {_paths(SYM_LEG, TRACE_BRIGHT, 8)}
    </g>
    <circle cx="{SYM_GATE[0]}" cy="{SYM_GATE[1]}" r="{SYM_GATE[2]}" fill="{TRACE_BRIGHT}"/>
    <circle cx="{SYM_GATE[0]}" cy="{SYM_GATE[1]}" r="{SYM_GATE[3]}" fill="{INK}"/>
  </g>
</svg>
"""


def readme_banner(dark: bool) -> str:
    """1600x400 README hero: mark, name, promise, restrained pipeline cue."""
    bg1, bg2 = ("#0F1B21", "#12262B") if dark else ("#FFFFFF", "#F4F1EA")
    text = PAPER_TEXT if dark else INK
    sub = "#9DB0A9" if dark else "#51616B"
    route = TRACE_BRIGHT if dark else TRACE
    tile = "#12262B" if dark else "#FFFFFF"
    tile_edge = "#2A3B42" if dark else "#E3E0D8"
    core = INK_DEEP if dark else PAPER
    mark_stem = PAPER_TEXT if dark else INK
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 400" role="img" aria-labelledby="bt bd">
  <title id="bt">Knovaryn — every training example, traced to its source</title>
  <desc id="bd">Knovaryn logo and promise: source spans converge through a quality gate into verified dataset rows.</desc>
  <!-- Generated by scripts/visuals/build_brand_assets.py — do not edit; rerun. -->
  <defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
    <stop offset="0" stop-color="{bg1}"/><stop offset="1" stop-color="{bg2}"/>
  </linearGradient></defs>
  <rect width="1600" height="400" fill="url(#bg)"/>
  <rect x="0.5" y="0.5" width="1599" height="399" fill="none" stroke="{tile_edge}"/>
  <!-- mark -->
  <g transform="translate(120,110) scale(2.8)">
    <g stroke-linecap="round" fill="none">
      {_paths(SYM_STEM, mark_stem, 9)}
      {_paths(SYM_ARM, route, 8)}
      {_paths(SYM_LEG, route, 8)}
    </g>
    <circle cx="{SYM_GATE[0]}" cy="{SYM_GATE[1]}" r="{SYM_GATE[2]}" fill="{route}"/>
    <circle cx="{SYM_GATE[0]}" cy="{SYM_GATE[1]}" r="{SYM_GATE[3]}" fill="{core}"/>
  </g>
  <!-- name + promise -->
  <text x="340" y="205" font-family="-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif" font-size="92" font-weight="700" fill="{text}" letter-spacing="-1">Knovaryn</text>
  <text x="344" y="262" font-family="-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif" font-size="31" fill="{sub}">Every training example, <tspan fill="{route}" font-weight="600">traced to its source.</tspan></text>
  <!-- restrained pipeline cue: spans -> gate -> rows -->
  <g transform="translate(345,316)" font-family="-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif" font-size="21" fill="{sub}">
    <rect x="0" y="0" width="196" height="42" rx="21" fill="{tile}" stroke="{tile_edge}"/>
    <text x="98" y="27" text-anchor="middle" fill="{sub}">source spans</text>
    <path d="M 208 21 H 244" stroke="{route}" stroke-width="3" stroke-linecap="round"/>
    <circle cx="258" cy="21" r="10" fill="{route}"/><circle cx="258" cy="21" r="4" fill="{core}"/>
    <path d="M 272 21 H 308" stroke="{route}" stroke-width="3" stroke-linecap="round"/>
    <rect x="320" y="0" width="196" height="42" rx="21" fill="{tile}" stroke="{tile_edge}"/>
    <text x="418" y="27" text-anchor="middle" fill="{sub}">verified rows</text>
  </g>
  <text x="1480" y="347" text-anchor="end" font-family="-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif" font-size="21" fill="{sub}">MCP-native · open source · Apache-2.0</text>
  <!-- provenance thread along the top -->
  <path d="M 120 64 H 1480" stroke="{route}" stroke-opacity="0.25" stroke-width="2" stroke-dasharray="1 14" stroke-linecap="round"/>
</svg>
"""


def readme_banner_narrow(dark: bool) -> str:
    """800x480 stacked README hero for narrow viewports (GitHub mobile).

    Same content as :func:`readme_banner` — mark, name, promise, restrained
    pipeline cue — arranged vertically so type stays legible when the image
    is rendered ~390 px wide (scale ≈ 0.49 keeps the promise ≥ 14 px).
    """
    bg1, bg2 = ("#0F1B21", "#12262B") if dark else ("#FFFFFF", "#F4F1EA")
    text = PAPER_TEXT if dark else INK
    sub = "#9DB0A9" if dark else "#51616B"
    route = TRACE_BRIGHT if dark else TRACE
    tile = "#12262B" if dark else "#FFFFFF"
    tile_edge = "#2A3B42" if dark else "#E3E0D8"
    core = INK_DEEP if dark else PAPER
    mark_stem = PAPER_TEXT if dark else INK
    mark_s = 3.4
    mark_tx = 400 - 36.5 * mark_s  # symbol content spans x 19..54
    mark_ty = 72 - 8.5 * mark_s  # symbol content starts at y 8.5
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 480" role="img" aria-labelledby="bt bd">
  <title id="bt">Knovaryn — every training example, traced to its source</title>
  <desc id="bd">Knovaryn logo and promise: source spans converge through a quality gate into verified dataset rows.</desc>
  <!-- Generated by scripts/visuals/build_brand_assets.py — do not edit; rerun. -->
  <defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
    <stop offset="0" stop-color="{bg1}"/><stop offset="1" stop-color="{bg2}"/>
  </linearGradient></defs>
  <rect width="800" height="480" fill="url(#bg)"/>
  <rect x="0.5" y="0.5" width="799" height="479" fill="none" stroke="{tile_edge}"/>
  <path d="M 64 40 H 736" stroke="{route}" stroke-opacity="0.25" stroke-width="2" stroke-dasharray="1 14" stroke-linecap="round"/>
  <g transform="translate({mark_tx:.1f},{mark_ty:.1f}) scale({mark_s})">
    <g stroke-linecap="round" fill="none">
      {_paths(SYM_STEM, mark_stem, 9)}
      {_paths(SYM_ARM, route, 8)}
      {_paths(SYM_LEG, route, 8)}
    </g>
    <circle cx="{SYM_GATE[0]}" cy="{SYM_GATE[1]}" r="{SYM_GATE[2]}" fill="{route}"/>
    <circle cx="{SYM_GATE[0]}" cy="{SYM_GATE[1]}" r="{SYM_GATE[3]}" fill="{core}"/>
  </g>
  <text x="400" y="300" text-anchor="middle" font-family="-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif" font-size="78" font-weight="700" fill="{text}" letter-spacing="-1">Knovaryn</text>
  <text x="400" y="348" text-anchor="middle" font-family="-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif" font-size="30" fill="{sub}">Every training example, <tspan fill="{route}" font-weight="600">traced to its source.</tspan></text>
  <g transform="translate(142,392)" font-family="-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif" font-size="21" fill="{sub}">
    <rect x="0" y="0" width="196" height="42" rx="21" fill="{tile}" stroke="{tile_edge}"/>
    <text x="98" y="27" text-anchor="middle" fill="{sub}">source spans</text>
    <path d="M 208 21 H 244" stroke="{route}" stroke-width="3" stroke-linecap="round"/>
    <circle cx="258" cy="21" r="10" fill="{route}"/><circle cx="258" cy="21" r="4" fill="{core}"/>
    <path d="M 272 21 H 308" stroke="{route}" stroke-width="3" stroke-linecap="round"/>
    <rect x="320" y="0" width="196" height="42" rx="21" fill="{tile}" stroke="{tile_edge}"/>
    <text x="418" y="27" text-anchor="middle" fill="{sub}">verified rows</text>
  </g>
  <text x="400" y="464" text-anchor="middle" font-family="-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif" font-size="17" fill="{sub}">MCP-native · open source · Apache-2.0</text>
</svg>
"""


def social_preview(kind: str) -> str:
    """1280x640 (GitHub) social preview source. ``kind``: github|docs|release."""
    titles = {
        "github": ("Knovaryn", ["Every training example,", "traced to its source."]),
        "docs": (
            "Knovaryn docs",
            [
                "Quality-gated SFT, preference, KTO, and",
                "evaluation datasets — provenance enforced.",
            ],
        ),
        "release": ("Knovaryn", ["Open-source, self-hosted,", "MCP-native training-data foundry."]),
    }
    title, sub_lines = titles[kind]
    sub_svg = "".join(
        f'\n  <text x="424" y="{372 + i * 44}" font-family="-apple-system, \'Segoe UI\', Helvetica, Arial, sans-serif" font-size="34" fill="#9DB0A9">{line}</text>'
        for i, line in enumerate(sub_lines)
    )
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 640" role="img" aria-labelledby="pt pd">
  <title id="pt">{title} — social preview</title>
  <desc id="pd">{title}: {" ".join(sub_lines)}</desc>
  <!-- Generated by scripts/visuals/build_brand_assets.py — do not edit; rerun. -->
  <rect width="1280" height="640" fill="{INK_DEEP}"/>
  <rect width="1280" height="640" fill="none" stroke="#2A3B42" stroke-width="2"/>
  <g transform="translate(96,140) scale(3.4)">
    <g stroke-linecap="round" fill="none">
      {_paths(SYM_STEM, PAPER_TEXT, 9)}
      {_paths(SYM_ARM, TRACE_BRIGHT, 8)}
      {_paths(SYM_LEG, TRACE_BRIGHT, 8)}
    </g>
    <circle cx="{SYM_GATE[0]}" cy="{SYM_GATE[1]}" r="{SYM_GATE[2]}" fill="{TRACE_BRIGHT}"/>
    <circle cx="{SYM_GATE[0]}" cy="{SYM_GATE[1]}" r="{SYM_GATE[3]}" fill="{INK_DEEP}"/>
  </g>
  <text x="420" y="290" font-family="-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif" font-size="88" font-weight="700" fill="{PAPER_TEXT}" letter-spacing="-1">{title}</text>{sub_svg}
  <g font-family="-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif" font-size="24" fill="#9DB0A9">
    <text x="424" y="500">Open source · Apache-2.0 · MCP-native · offline-first</text>
  </g>
  <path d="M 96 560 H 1184" stroke="{TRACE_BRIGHT}" stroke-opacity="0.3" stroke-width="3" stroke-dasharray="2 16" stroke-linecap="round"/>
</svg>
"""


SVG_TARGETS = {
    "logo-primary.svg": lambda: lockup(INK, TRACE, PAPER),
    "logo-primary-dark.svg": lambda: lockup(PAPER_TEXT, TRACE_BRIGHT, INK_DEEP),
    "logo-monochrome-dark.svg": lambda: lockup(INK, INK, PAPER, mono=True),
    "logo-monochrome-light.svg": lambda: lockup(PAPER_TEXT, PAPER_TEXT, INK_DEEP, mono=True),
    "logo-symbol.svg": lambda: symbol(INK, TRACE, PAPER),
    "logo-wordmark.svg": lambda: wordmark(INK),
    "logo-stacked.svg": stacked,
    "favicon.svg": favicon,
    "github-readme-banner.svg": lambda: readme_banner(dark=False),
    "github-readme-banner-dark.svg": lambda: readme_banner(dark=True),
    "github-readme-banner-narrow.svg": lambda: readme_banner_narrow(dark=False),
    "github-readme-banner-narrow-dark.svg": lambda: readme_banner_narrow(dark=True),
    "github-social-preview-source.svg": lambda: social_preview("github"),
    "docs-social-preview-source.svg": lambda: social_preview("docs"),
    "release-social-preview-source.svg": lambda: social_preview("release"),
}

# stem → (source svg, width, height, device_scale)
RASTER_TARGETS = {
    "favicon-32.png": ("favicon.svg", 32, 32, 3),
    "favicon-192.png": ("favicon.svg", 192, 192, 2),
    "app-icon.png": ("favicon.svg", 512, 512, 2),
    "github-avatar.png": ("favicon.svg", 500, 500, 2),
    "github-social-preview.png": ("github-social-preview-source.svg", 1280, 640, 1),
    "docs-social-preview.png": ("docs-social-preview-source.svg", 1200, 630, 1),
    "release-social-preview.png": ("release-social-preview-source.svg", 1200, 630, 1),
}


def _render_png(browser, svg_path: Path, dest: Path, w: int, h: int) -> None:
    html = (
        f'<!doctype html><body style="margin:0">'
        f'<img src="{svg_path.name}" width="{w}" height="{h}"></body>'
    )
    tmp = dest.with_suffix(".html")
    tmp.write_text(html)
    # exact-size raster: device_scale_factor 1 keeps every PNG at its
    # declared pixel dimensions (the SVG is vector, so it stays sharp)
    page = browser.new_page(viewport={"width": w, "height": h}, device_scale_factor=1)
    page.goto(tmp.as_uri())
    page.wait_for_timeout(60)
    page.locator("img").screenshot(path=str(dest))
    page.close()
    tmp.unlink()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify outputs match a fresh build")
    args = ap.parse_args()

    BRAND.mkdir(parents=True, exist_ok=True)
    failures: list[str] = []

    with tempfile.TemporaryDirectory(prefix="knv-brand-") as td:
        tmp = Path(td)
        fresh: dict[str, bytes] = {}
        for name, builder in SVG_TARGETS.items():
            fresh[name] = builder().encode("utf-8")
        for _name, (src, _w, _h, _scale) in RASTER_TARGETS.items():
            (tmp / src).write_bytes(fresh[src])
        from playwright.sync_api import sync_playwright

        with sync_playwright() as p:
            browser = p.chromium.launch()
            for name, (src, w, h, _scale) in RASTER_TARGETS.items():
                _render_png(browser, tmp / src, tmp / name, w, h)
            browser.close()
        for name in RASTER_TARGETS:
            fresh[name] = (tmp / name).read_bytes()

        for name, data in sorted(fresh.items()):
            target = BRAND / name
            if args.check:
                old = target.read_bytes() if target.is_file() else b""
                if hashlib.sha256(old) != hashlib.sha256(data):
                    failures.append(
                        f"{name}: drifted — rerun scripts/visuals/build_brand_assets.py"
                    )
            else:
                target.write_bytes(data)
                print(f"built {name} ({len(data)} bytes)")

    if failures:
        print("\n".join(f"FAIL: {f}" for f in failures), file=sys.stderr)
        return 1
    print("brand assets in sync" if args.check else "all brand assets built")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
